# Generated by Django 4.0.1 on 2022-01-05 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30)),
                ('birth_date', models.DateField(default=None)),
                ('password', models.CharField(blank=True, max_length=20, validators=[django.core.validators.MinLengthValidator(4)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
